### REGISTRAR USUARIO ###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456",
  "role": "ADMIN"
}

###

### LOGIN ###
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@instituto.com",
  "password": "123456"
}

###

### TOKEN ID ###
@token = {{login.response.body.token}}

###

### OBTENER INFORMACIÓN DE USUARIO ###

GET http://localhost:3000/auth/userInfo
Authorization: Bearer {{token}}